#!/bin/sh

echo "Switching to branch master"
git checkout master

echo "Building app"
npm run build

echo "Deploying files to server"
rsync -avP build/ kernel@139.162.42.38:/home/kernel/client
echo "Deployment complete"