#!/bin/sh

echo "Switching to branch master"
git checkout master

echo "Building app"
npm run build

echo "Deploying files to server"
rsync -avP build/ kernel@medibee.com.bd:/var/www/medibee.com.bd/
echo "Deployment complete"