#!/bin/sh

echo "Switching to branch master"
git checkout master

echo "Building app"
npm run build

echo "Deploying files to server"
rsync -avP build/ kernel@coursebee.com:/var/www/coursebee.com/
echo "Deployment complete"